spring:
  config:
    name: application
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    tomcat:
      max-active: 10
      max-idle: 10000
      max-wait: 10000
      test-on-borrow: true
    url: jdbc:h2:file:${dataBaseUrl}
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver

dataBaseUrl: ./h2/alerts_db;DB_CLOSE_ON_EXIT=FALSE

# The following properties, initialDelay and fixedDelay are used in the example class, ScheduledServiceAction
initialDelay: 10000
fixedDelay: 60000

#Remove this password from here and pass it from command line -Djasypt.encryptor.password=password
#How to generate those encrpyted values? 
## We will use Jasypt for that! Go to http://www.jasypt.org/ and download the latest version. 
## When you are done, go into jasypt\bin and use the encrypt.sh or encrypt.bat to encrypt your variables. 
## There are several algorithms to pick but I will leave it as default and only give my property value and secret to encrpyt it.
jasypt:
  encryptor:
    password: password

server:
  port: 8080
  tomcat:
    accessLog.enabled: true
    basedir: "${LOG_PATH}/Application"
    accessLogPattern: "%h %l %u %t \"%r\" %s %b %D"


